#!/bin/bash
set -xeo pipefail
args=("$@")
USERNAME=${args[0]}
PASSWORD=${args[1]}
if [ -z "$USERNAME" ]; then
    echo "Please set USERNAME"
    exit 1
fi
if [ -z "$PASSWORD" ]; then
    GITLAB_ROOT_GENERATED_PASSWORD=$(jq -r '.gitlab_root_generated_password' "$HOME/.pic/gitlab.json")
    PASSWORD=$GITLAB_ROOT_GENERATED_PASSWORD
fi
if [ -z "$PASSWORD" ]; then
    echo "Please set PASSWORD"
    exit 1
fi
sysctl fs.inotify.max_user_instances=1280
sysctl fs.inotify.max_user_watches=655360
echo "Installing Grafana"
# uninstall promtail, loki, grafana if they exist. Wait for them to be deleted.
helm uninstall --namespace loki promtail || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=promtail
helm uninstall --namespace loki loki || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=loki
helm uninstall --namespace loki grafana || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=grafana

helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
kubectl get namespace loki || kubectl create namespace loki
kubectl get secret --namespace loki grafana || \
    kubectl create secret generic grafana --namespace loki --from-literal=admin-password=$PASSWORD --from-literal=admin-user=$USERNAME --from-literal=ldap-toml=""
helm upgrade --install --namespace loki promtail grafana/promtail
helm upgrade --install --namespace loki loki grafana/loki \
    --version 5.47.2 \
    --set "singleBinary.replicas=1" \
    --set "singleBinary.persistence.storageClass=local-path" \
    --set "loki.commonConfig.replication_factor=1" \
    --set "loki.storage.type=filesystem" \
    --set "read.persistence.storageClass=local-path" \
    --set "backend.persistence.storageClass=local-path" \
    --set "monitoring.lokiCanary.enabled=false" \
    --set "monitoring.selfMonitoring.enabled=false" \
    --set "test.enabled=false" \
    --set "write.persistence.storageClass=local-path" --set "loki.auth_enabled=false"
cat <<EOF > ./grafana-values.yaml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-headless:3100
        access: proxy
        isDefault: true
EOF
helm upgrade --install --set "admin.existingSecret=grafana" --namespace loki grafana grafana/grafana --values ./grafana-values.yaml
rm ./grafana-values.yaml
jq -n --arg password "$PASSWORD" --arg username "$USERNAME" '{"username":$username,"password":$password}' > $HOME/.pic/grafana-admin.json
echo "Grafana admin password: $PASSWORD"
