#!/bin/bash
set -e -o pipefail
args=("$@")
USERNAME=${args[0]}
PASSWORD=${args[1]}
if [ -z "$USERNAME" ]; then
    echo "Please set USERNAME"
    exit 1
fi
if [ -z "$PASSWORD" ]; then
    GITLAB_ROOT_GENERATED_PASSWORD=$(jq -r '.gitlab_root_generated_password' "$HOME/.pic/gitlab.json")
    PASSWORD=$GITLAB_ROOT_GENERATED_PASSWORD
fi
if [ -z "$PASSWORD" ]; then
    echo "Please set PASSWORD"
    exit 1
fi
sysctl fs.inotify.max_user_instances=1280
sysctl fs.inotify.max_user_watches=655360
echo "Installing Grafana"
# uninstall promtail, loki, grafana if they exist. Wait for them to be deleted.
helm uninstall --namespace loki promtail || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=promtail
helm uninstall --namespace loki loki || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=loki
helm uninstall --namespace loki grafana || true
kubectl wait --for=delete --timeout=60s --namespace loki pod -l app=grafana

helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
kubectl get namespace loki || kubectl create namespace loki
kubectl get secret --namespace loki grafana || \
    kubectl create secret generic grafana --namespace loki --from-literal=admin-password=$PASSWORD --from-literal=admin-user=$USERNAME --from-literal=ldap-toml=""
# helm install grafana grafana/grafana --namespace=loki
helm upgrade --install --namespace loki promtail grafana/promtail
helm upgrade --install --namespace loki loki grafana/loki           \
    --set       "read.persistence.storageClass=local-path"      \
    --set       "backend.persistence.storageClass=local-path"   \
    --set       "write.persistence.storageClass=local-path" --set "loki.auth.enabled=false"
cat <<EOF > ./grafana-values.yaml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki-read.loki:3100
        access: proxy
        isDefault: true
EOF
helm upgrade --install --set "admin.existingSecret=grafana" --namespace loki grafana grafana/grafana --values ./grafana-values.yaml
rm ./grafana-values.yaml
# PASSWORD=$(kubectl get secret --namespace loki grafana -o jsonpath="{.data.admin-password}" | base64 --decode)
jq -n --arg password "$PASSWORD" --arg username "$USERNAME" '{"username":$username,"password":$password}' > $HOME/.pic/grafana-admin.json
echo "Grafana admin password: $PASSWORD"
