#!/bin/bash
set -e
echo
source .env
args=("$@")
for arg in "$@"; do
    echo "arg: $arg"
    if [ -z "$arg" ]; then
        break;
    fi
    FOLDER=$arg
    (cd "$FOLDER" && pwd && terraform init >> terraform-init.log && rm terraform-init.log)
done
