#! /bin/bash
isRoot=$(whoami)
if [ "$isRoot" != "root" ]; then
    echo "Please run as root"
    exit 1
fi
args=("$@")
arg1=${args[0]}
if [ "$arg1" == "update" ]; then
    echo "Updating PiCloud"
    exit 0
fi
if [ "$arg1" == "install" ]; then
    echo "Installing Docker"
    curl -fsSL https://get.docker.com -o install-docker.sh
    chmod +x install-docker.sh
    ./install-docker.sh
    echo "Installed Docker"
    rm install-docker.sh
    exit 0
fi
if [ "$arg1" == "remove" ]; then
    echo "Removing PiCloud"
    exit 0
fi
if [ "$arg1" == "start" ]; then
    echo "Starting PiCloud"
    exit 0
fi
if [ "$arg1" == "stop" ]; then
    echo "Stopping PiCloud"
    exit 0
fi
if [ "$arg1" == "restart" ]; then
    echo "Restarting PiCloud"
    exit 0
fi
if [ "$arg1" == "status" ]; then
    echo "Status of PiCloud"
    exit 0
fi
if [ "$arg1" == "help" ]; then
    echo "Help for PiCloud"
    echo "Usage: ./pic [command]"
    echo "Commands:"
    echo "  update"
    echo "  install"
    echo "  remove"
    echo "  start"
    echo "  stop"
    echo "  restart"
    echo "  status"
    echo "  help"

    exit 0
fi
./pic help
