apiVersion: apps/v1
kind: Deployment
metadata:
  name: pic-test-csi-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pic-test-csi-s3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pic-test-csi-s3
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          for i in 1 2 3 4 5 6 7 8 9 10 ; do
            echo $i
            wget "https://raw.githubusercontent.com/qtvhao/picloud/main/tests/steffen-b-qDZ-Xd8dX6w-unsplash.jpg" -O "/tmp/dir/$i.png"
          done
          sleep 1000
        image: busybox
        name: pic-test-csi-s3
        volumeMounts:
        - mountPath: /tmp/dir/
          name: tmp-data
      volumes:
      - name: tmp-data
        persistentVolumeClaim:
          claimName: pic-test-pvc
          readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pic-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem
