#!/bin/bash
set -e -o pipefail

args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a node ip for the new machine."
    echo "Usage: ./pic auto-join IDENTIFY_FILE"
    exit 1
fi
LOGS_DIR="$HOME/.pic/logs"
if [ ! -f "NODES" ]; then
    ./pic discover-nodes $IDENTIFY_FILE
fi
echo "" >> NODES
JOINED_NODES=""
cat NODES | while IFS= read -r node; do
    if [ -z "$node" ]; then
        continue
    fi
    ssh-keygen -R "$node" > /dev/null 2>&1 || true
    ssh-keyscan "$node" >> /root/.ssh/known_hosts 2>&1
    echo "Joining node $node"
    ( time (./pic join-k3s "$node" $IDENTIFY_FILE) | tee $LOGS_DIR/join-k3s.log)
    JOINED_NODES="$JOINED_NODES $node"
done
echo "All nodes are joined: $JOINED_NODES"
echo
cat NODES | while IFS= read -r node; do
    if [ -z "$node" ]; then
        continue
    fi
    (kubectl get node -o wide | grep "$node") || (echo "Node $node is not ready" && exit 1)
    echo "Node $node is ready"
done
echo "All nodes are ready"
