#!/bin/bash
set -e -o pipefail

args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a node ip for the new machine."
    echo "Usage: ./pic auto-join IDENTIFY_FILE"
    exit 1
fi
if [ ! -f "NODES" ]; then
    ./pic discover-nodes $IDENTIFY_FILE
fi
echo "" >> NODES
cat NODES | while IFS= read -r node; do
    if [ -z "$node" ]; then
        continue
    fi
    ssh-keygen -R "$node" || true
    ssh-keyscan "$node" >> /root/.ssh/known_hosts
    ( time (./pic join-k3s "$node" $IDENTIFY_FILE) | tee $LOGS_DIR/join-k3s.log) &
done
wait $(jobs -p)
echo "All nodes are ready"