#!/bin/bash

which bc > /dev/null 2>&1 || {
    apt-get update > /dev/null 2>&1
    apt-get install -y bc > /dev/null 2>&1
}

IDENTIFY_FILE="$HOME/id_rsa"
echo "" > NODES
K8S_MASTER_NODE_IP=$(hostname -I | cut -d' ' -f1)
nodesOnLan=$(./pic list-nodename $IDENTIFY_FILE | grep -v virtualbox | awk '{print $1}' | tr '\n' ' ')
echo "nodesOnLan: $nodesOnLan"
for node in $nodesOnLan; do
    if [ "$K8S_MASTER_NODE_IP" == "$node" ]; then
        continue
    fi
    if [ -z "$node" ]; then
        continue
    fi
    echo "Checking $node"
    echo "$node" >> NODES
    ssh-keygen -R "$node" || true
    ssh-keyscan "$node" >> /root/.ssh/known_hosts
    THE_HOSTNAME=$(ssh -i $IDENTIFY_FILE $node hostname)
    echo "$THE_HOSTNAME"
done
