#!/bin/bash

echo "- Images:"
NODES=$(kubectl get nodes -o json | jq -r ".items")
STATUS_IMAGES=$(echo "$NODES" | jq -r ".[].status.images" | jq -r ".[]")
SORT_BY_sizeBytes_DESC=$(echo "$STATUS_IMAGES" | jq -s 'sort_by(.sizeBytes) | reverse' | jq -r '.[]')
NAMES=$(echo $SORT_BY_sizeBytes_DESC | jq -r ".names[1]" | uniq)
echo "$NAMES" | tee images.txt
echo

echo "- Registries:"
REGISTRIES=$(echo "$NAMES" | sed 's/\/.*//g' | sort | uniq)
echo "$REGISTRIES" | tee registries.txt
