#!/bin/bash

args=("$@")
IMAGE_NAME=${args[0]}

set -e -o pipefail

if [ -z "$IMAGE_NAME" ]; then
    echo "Usage: ./pull-image <image-name>"
    exit 1
fi
RANDOM_CONTAINER_NAME=$(openssl rand -hex 16)
echo "Pull image $IMAGE_NAME to local registry"

time (kubectl run \
    --image="$IMAGE_NAME" "pull-$RANDOM_CONTAINER_NAME" \
    --restart=Never --command -- sh -c "echo 'This is a temporary pod to install gitlab. It will be removed after installation is done.'")

while kubectl get pod "pull-$RANDOM_CONTAINER_NAME" >/dev/null 2>&1; do
    POD_STATUS=$(kubectl get pod "pull-$RANDOM_CONTAINER_NAME" -o json | jq -r '.status.phase')
    Succeeded=$(echo "$POD_STATUS" | grep Succeeded || true)
    Failed=$(echo "$POD_STATUS" | grep Failed || true)
    if [ ! -z "$Failed" ]; then
        echo "Pod failed, exiting"
        exit 1
    fi
    if [ ! -z "$Succeeded" ]; then
        echo "Pod succeeded, exiting"
        break
    fi
    echo "Pod is not ready yet. Waiting for 1 second. Current status: $POD_STATUS"
    sleep 1
done
