#!/bin/bash

args=("$@")
NODE_NAME=${args[0]}

set -e -o pipefail
echo "Usage: ./pull-image.sh <image-name>"
# gitlab-images.txt
GITLAB_IMAGES_TXT="./gitlab-images.txt"
while read -r line; do
    ./pic pull-image $line $NODE_NAME &
done < "$GITLAB_IMAGES_TXT"
wait
exit 0
