#!/bin/bash

args=("$@")
IMAGE_NAME=${args[0]}
NODE_NAME=${args[1]}
if [ -z "$NODE_NAME" ]; then
    echo "Usage: ./pull-image <image-name> <node-name>"
    exit 1
fi
set -e -o pipefail

if [ -z "$IMAGE_NAME" ]; then
    echo "Usage: ./pull-image <image-name>"
    exit 1
fi
RANDOM_CONTAINER_NAME=$(openssl rand -hex 16)
echo "Pull image $IMAGE_NAME to local registry"

(kubectl run \
    --image="$IMAGE_NAME" "pull-$RANDOM_CONTAINER_NAME" \
    --restart=Never --command -- sh -c "echo 'This is a temporary pod to install gitlab. It will be removed after installation is done.'")

while true; do
    sleep 10
    POD_STATUS=$(kubectl get pod "pull-$RANDOM_CONTAINER_NAME" -o json | jq -r '.status.phase')
    Pending=$(echo "$POD_STATUS" | grep Pending || true)
    if [ ! -z "$Pending" ]; then
        # echo "Pod is pending, exiting"
        continue;
    fi
    Succeeded=$(echo "$POD_STATUS" | grep Succeeded || true)
    Failed=$(echo "$POD_STATUS" | grep Failed || true)
    if [ ! -z "$Failed" ]; then
        echo "Pod failed, exiting"
        break
    fi
    if [ ! -z "$Succeeded" ]; then
        echo "Pod succeeded, exiting"
        break
    fi
    echo "Pod is not ready yet. Waiting for 1 second. Current status: $POD_STATUS"
done
kubectl delete pod "pull-$RANDOM_CONTAINER_NAME"
