#!/bin/bash
set -xeo pipefail
MACHINES=""
MACHINES="$MACHINES 18:60:24:db:a0:72,192.168.1.104,prodesk"
MACHINES="$MACHINES 8c:dc:d4:34:0c:f0,192.168.1.102,z440"
MACHINES="$MACHINES 64:00:6a:7c:08:75,192.168.1.103,dell"

echo "MACHINES: $MACHINES"
./pic fai schnworks qtvhao
./pic auto-pxe /root/id_rsa "$MACHINES"
