#!/bin/bash
set -e -o pipefail

TUNNEL_NAMESPACE=default ./pic expose https     metrics-server.kube-system              443 404
TUNNEL_NAMESPACE=default ./pic expose http      traefik.kube-system                     80
cat ~/.pic/expose-picloud-default.json | jq
rm ~/.pic/expose-picloud-default.json

TUNNEL_NAMESPACE=default2 ./pic expose https     metrics-server.kube-system             443 404
TUNNEL_NAMESPACE=default2 ./pic expose http     traefik.kube-system                     80
cat ~/.pic/expose-picloud-default2.json | jq
rm ~/.pic/expose-picloud-default2.json

TUNNEL_NAMESPACE=default3 ./pic expose https     metrics-server.kube-system             443 404
TUNNEL_NAMESPACE=default3 ./pic expose http      traefik.kube-system                    80     404 "" "true"
cat ~/.pic/expose-picloud-default3.json | jq
rm ~/.pic/expose-picloud-default3.json

./pic wait deploy cloudflared-default  default  Available
./pic wait deploy cloudflared-default2 default2 Available
./pic wait deploy cloudflared-default3 default3 Available

echo; echo "All pods are running"
