#!/bin/bash

set -xeo pipefail
PIC_DIR="$HOME/.pic"
LOGS_DIR="$PIC_DIR/logs/"
# echo;time ./pic auto-join $IDENTIFY_FILE | tee $LOGS_DIR/auto-join.log
set -e -o pipefail
IDENTIFY_FILE="$HOME/id_rsa"
time ./pic recommended2 $IDENTIFY_FILE
# echo;time ./pic reinstall-k3s $IDENTIFY_FILE | tee $LOGS_DIR/reinstall-k3s.log;( time (./pic install-gitlab $IDENTIFY_FILE | tee $LOGS_DIR/gitlab.log))

kubectl logs gitlab-postgresql-0 -n gitlab-ns
./pic git-folk https://github.com/qtvhao/picloud.git "$IDENTIFY_FILE"
echo "Folk and push to gitlab successfully"
while ! ./pic succeed-pipeline root%2Fpicloud main; do
    echo "Waiting for gitlab runner to be ready"
    STATUS=$(./pic get-pipelines root%2Fpicloud main | jq -r ".[0].status")
    EXPECTED_STATUS="running"
    if [ "$STATUS" == "$EXPECTED_STATUS" ]; then
        echo "Pipeline is running"
        break;
    fi
    sleep 2
done
