#!/bin/bash

set -xeo pipefail
PIC_DIR="$HOME/.pic"
LOGS_DIR="$PIC_DIR/logs/"
# echo;time ./pic auto-join $IDENTIFY_FILE | tee $LOGS_DIR/auto-join.log
set -e -o pipefail
IDENTIFY_FILE="$HOME/id_rsa"
# time ./pic recommended2 $IDENTIFY_FILE
echo;time ./pic reinstall-k3s $IDENTIFY_FILE | tee $LOGS_DIR/reinstall-k3s.log;( time (./pic install-gitlab $IDENTIFY_FILE | tee $LOGS_DIR/gitlab.log))

./pic git-folk https://github.com/qtvhao/picloud.git "$HOME/id_rsa"
echo "Folk and push to gitlab successfully. Pipeline is successful."
