#!/bin/bash

PIC_DIR="$HOME/.pic"
LOGS_DIR="$PIC_DIR/logs/"
time ./pic reinstall-k3s ../id_rsa > /dev/null
# echo;time ./pic auto-join $IDENTIFY_FILE | tee $LOGS_DIR/auto-join.log
set -e -o pipefail
apt install vnstat -y
while ! ./pic pull-image busybox; do
    sleep 2
done

echo; ./pic redis | tee $LOGS_DIR/redis.log
time ./pic pull-image
# this will reduce the time to install gitlab from 3m28 to 2m41
echo;time ./pic install-gitlab ../id_rsa | tee $LOGS_DIR/gitlab.log
rm -rf $LOGS_DIR/gitlab.log
# ./pic wait pod          redis-master-0                  default Ready
# ./pic wait pod          redis-replicas-0                  default Ready
