#!/bin/bash
set -xe -o pipefail

IDENTIFY_FILE="$HOME/id_rsa"
time (./pic recommended2 $HOME/id_rsa | tee recommended.log)
timeout 600 ./pic wait deploy pic-test-csi-s3 default Available
timeout 20 kubectl logs deploy/pic-test-csi-s3 -f || true
