#!/bin/bash
set -xeo pipefail
time (./pic reinstall-k3s $HOME/id_rsa | tee reinstall-k3s.log)
time ./pic recommended $HOME/id_rsa 2>&1 | tee recommended.log
# real    9m53.940s
# user    2m12.228s
# sys     0m18.049s
echo "Recommended packages installed"
