#!/bin/bash
set -xeo pipefail
time (./pic reinstall-k3s $HOME/id_rsa | tee reinstall-k3s.log)
time ./pic recommended $HOME/id_rsa 2>&1 | tee recommended.log
# real    11m16.051s
# user    3m15.124s
# sys     0m32.637s
echo "Recommended packages installed"
