#!/bin/bash
time (./pic reinstall-k3s $HOME/id_rsa | tee reinstall-k3s.log)
time ./pic recommended $HOME/id_rsa | tee recommended.log
# it costs 10 minutes to install recommended packages

echo "Recommended packages installed"
