metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '2C:59:E5:04:C4:51', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.1.113, mac: '2C:59:E5:04:C4:51', disk: sda, network_interface: eno1}
