FROM fai-setup-base

RUN mkdir -p /srv/fai/nfsroot/etc/apt/sources.list.d/
RUN mkdir -p /srv/fai/nfsroot/usr/share/keyrings/
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN curl https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /srv/fai/nfsroot/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
RUN curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /srv/fai/nfsroot/usr/share/keyrings/cloudflare-main.gpg
RUN echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bookworm main' | tee /srv/fai/nfsroot/etc/apt/sources.list.d/cloudflared.list
RUN mkdir -p /srv/fai/nfsroot/etc/systemd/sleep.conf.d/
RUN mkdir -p /srv/fai/config/
COPY fai/fai-bookworm/ /srv/fai/config/fai-bookworm/
COPY fai/files/etc/resolv.conf /srv/fai/nfsroot/etc/resolv.conf
RUN cp /etc/apt/sources.list /srv/fai/config/fai-bookworm/apt/sources.list
RUN cp /etc/fai/nfsroot.conf /srv/fai/config/fai-bookworm/nfsroot.conf
RUN sed -i 's%^\(NFSROOT\)=.*%\1=/srv/fai/nfsroot%' /srv/fai/config/fai-bookworm/nfsroot.conf
RUN chmod +x /usr/sbin/policy-rc.d
