#!/bin/bash
args=("$@")
IP_ADDRESS=${args[0]}
IDENTIFY_FILE=${args[1]}
if [ -z "$IP_ADDRESS" ]; then
    echo "IP_ADDRESS is empty. Specify a IP address for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
if [ ! -f "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE does not exist. Specify a identify file for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
NETWORK_INTERFACES=$(ssh -i $IDENTIFY_FILE $IP_ADDRESS "ip address | grep -E '^[0-9]+: ' | awk '{print \$2}' | sed 's/://g' | grep -v veth | grep -v lo | grep -v docker | grep -v br- | grep -v vnet | grep -v flannel | grep -v cni | grep -v tun")
FIRST_NETWORK_INTERFACE=$(echo "$NETWORK_INTERFACES" | head -n 1)
MAC_ADDRESS=$(ssh -i $IDENTIFY_FILE $IP_ADDRESS "cat /sys/class/net/$FIRST_NETWORK_INTERFACE/address")
echo "$MAC_ADDRESS"
