#!/bin/bash
set -e
echo "FROM kasmweb/core-ubuntu-jammy:1.14.0" > Dockerfile
# wget -O fai-project.gpg https://fai-project.org/download/2BF8D9FE074BCDE4.gpg
# cp fai-project.gpg /etc/apt/trusted.gpg.d/
# echo "deb http://fai-project.org/download buster koeln" > /etc/apt/sources.list.d/fai.list
# apt-get update
# aptitude install fai-quickstart
echo "USER root" >> Dockerfile
echo "RUN apt-get update && apt-get install -y wget" >> Dockerfile
echo "RUN wget -O fai-project.gpg https://fai-project.org/download/2BF8D9FE074BCDE4.gpg" >> Dockerfile
echo "RUN cp fai-project.gpg /etc/apt/trusted.gpg.d/" >> Dockerfile
echo "RUN echo \"deb http://fai-project.org/download buster koeln\" > /etc/apt/sources.list.d/fai.list" >> Dockerfile
echo "RUN apt-get update" >> Dockerfile
echo "RUN apt install fai-quickstart -y" >> Dockerfile
# sed -i -e 's/^#deb/deb/' /etc/fai/apt/sources.list
# sed -i -e 's/#LOGUSER/LOGUSER/' /etc/fai/fai.conf
echo "RUN sed -i -e 's/^#deb/deb/' /etc/fai/apt/sources.list" >> Dockerfile
echo "RUN sed -i -e 's/#LOGUSER/LOGUSER/' /etc/fai/fai.conf" >> Dockerfile
echo "ENTRYPOINT [\"/bin/bash\"]" >> Dockerfile
docker build -t fai .
rm Dockerfile
rm fai-mirror.log || true
rm fai-setup.log || true
rm fai-checkpkgs.log || true
docker rm -f fai || true
docker image inspect fai-setup > /dev/null 2>&1 || \
    (docker run --name fai --privileged -it fai fai-setup -v) > fai-setup.log
docker image inspect fai-setup > /dev/null 2>&1 || \
    docker commit fai fai-setup
args=("$@")
HOSTNAME=${args[0]}
echo "HOSTNAME: $HOSTNAME"
# 
rm -rf ~/fai/
docker rm -f fai-mk-configspace || true
docker run --name fai-mk-configspace    -v ~/fai:/srv/fai/config --privileged -it fai-setup fai-mk-configspace
docker rm -f fai-setup || true ;\
(docker run --name fai-setup            -v ~/fai:/srv/fai/config --privileged -it --entrypoint /bin/bash fai-setup fai-mirror -v /srv/$HOSTNAME) > fai-mirror.log
(docker run --name fai-checkpkgs        -v ~/fai:/srv/fai/config --privileged -it --entrypoint /bin/bash fai-setup checkpkgs /srv/$HOSTNAME) > fai-checkpkgs.log
exit 0
# docker run --name fai -v ~/fai:/srv/fai/config --privileged -it fai-setup fai-cd -m /tmp/ $HOSTNAME
