#!/bin/bash
set -eo pipefail
args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic list-nodename IDENTIFY_FILE"
    exit 1
fi
chmod 600 "$IDENTIFY_FILE"

ssh-keygen -l -f "$IDENTIFY_FILE" > /dev/null 2>&1 || (echo "IDENTIFY_FILE is not a valid identify file." && exit 1)

LIST_IP_ADDRESSES=$(./pic list-ssh-addresses 2>/dev/null)
echo "LIST_IP_ADDRESSES: $LIST_IP_ADDRESSES" >&2
echo
while IFS= read -r IP_ADDRESS; do
    if [ -z "$IP_ADDRESS" ]; then
        continue
    fi
    (timeout 30 ssh -T -i "$IDENTIFY_FILE" \
        -o ConnectTimeout=0 \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
            "$IP_ADDRESS" > /dev/null 2>/dev/null && echo "$IP_ADDRESS") &
done <<< "$LIST_IP_ADDRESSES"
wait
