#!/bin/bash
args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic list-nodename IDENTIFY_FILE"
    exit 1
fi
chmod 600 "$IDENTIFY_FILE"
LIST_IP_ADDRESSES=$(./pic list-ssh-addresses)
while IFS= read -r IP_ADDRESS; do
    if [ -z "$IP_ADDRESS" ]; then
        continue
    fi
    (timeout 2 ssh -T -i "$IDENTIFY_FILE" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
            "$IP_ADDRESS" > /dev/null 2>&1 && echo "$IP_ADDRESS") &
done <<< "$LIST_IP_ADDRESSES"
wait
