#!/bin/bash
args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic list-nodename IDENTIFY_FILE"
    exit 1
fi
chmod 600 "$IDENTIFY_FILE"
LIST_AUTHENTICATED_ADDRESSES=$(time ./pic list-authenticated-addresses $IDENTIFY_FILE)
echo "LIST_AUTHENTICATED_ADDRESSES: $LIST_AUTHENTICATED_ADDRESSES" >&2
echo
for IP_ADDRESS in $LIST_AUTHENTICATED_ADDRESSES; do
    if [ -z "$IP_ADDRESS" ]; then
        continue
    fi
    ssh-keygen -R $IP_ADDRESS > /dev/null 2>&1 || true
    ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts 2>&1 || true
    echo "Checking if $IP_ADDRESS is available" >&2
    ./pic print-available-node "$IP_ADDRESS" "$IDENTIFY_FILE" &
done
wait
