#!/bin/bash

MAX=254
for i in `seq 2 $MAX`; do
    IP_ADDRESS="192.168.1.$i"
    # set timeout 2 seconds for wireless network
    (ping -c1 -w3 $IP_ADDRESS >/dev/null 2>/dev/null && echo $IP_ADDRESS) &
done
wait
