#!/bin/bash

MAX=254
for i in `seq 2 $MAX`; do
    IP_ADDRESS="192.168.1.$i"
    # set timeout 2 seconds for wireless network
    (timeout .5 nc -z $IP_ADDRESS 22 >/dev/null 2>/dev/null && echo $IP_ADDRESS) &
done
wait
