#!/bin/bash
args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic list-nodename IDENTIFY_FILE"
    exit 1
fi
chmod 600 "$IDENTIFY_FILE"
MAX=254
echo
for i in `seq 2 $MAX`; do
    ./pic print-available-node "192.168.1.$i" "$IDENTIFY_FILE" &
done
wait
echo
echo
