#!/bin/bash
set -xeo pipefail
args=("$@")
IP_ADDRESS=${args[0]}
IDENTIFY_FILE=${args[1]}
if [ -z "$IP_ADDRESS" ]; then
    echo "IP_ADDRESS is empty. Specify a IP address for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
if [ -z "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE is empty. Specify a identify file for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
if [ ! -f "$IDENTIFY_FILE" ]; then
    echo "IDENTIFY_FILE does not exist. Specify a identify file for the new machine."
    echo "Usage: ./pic print-available-node IP_ADDRESS IDENTIFY_FILE"
    exit 1
fi
echo "Checking if $IP_ADDRESS dmidecode is available" >&2
ssh \
    -o ConnectTimeout=0 \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "dmidecode" >&2 > /dev/null || exit 0
echo "Getting product name from $IP_ADDRESS" >&2
PRODUCT_NAME=$(ssh \
    -o ConnectTimeout=0 \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "dmidecode" | grep "Product Name:" | head -n1 | sed 's/Product Name: //g' \
    | sed "s/[^[:alnum:]-]/-/g" \
    | sed -e "s/^-//g" \
    | sed -e "s/-$//g" \
    | tr '[:upper:]' '[:lower:]') || exit 0
if [ -z "$PRODUCT_NAME" ]; then
    exit 0
fi
echo "Got product name: $PRODUCT_NAME" >&2
BOOT_TIME=$(ssh -T \
    -o ConnectTimeout=0 \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "stat -c %W /var/log/fai/localhost/last/boot.log")
HUMAN_DIFF_SECONDS=$(echo "$(date +%s) - $BOOT_TIME" | bc)
echo "The machine $IP_ADDRESS was booted $HUMAN_DIFF_SECONDS seconds ago" >&2
echo "$IP_ADDRESS "$HUMAN_DIFF_SECONDS"_seconds_ago $PRODUCT_NAME"
