#!/bin/bash
args=("$@")
IP_ADDRESS=${args[0]}
IDENTIFY_FILE=${args[1]}

timeout 5 ping -c1 $IP_ADDRESS > /dev/null 2>&1 || exit 0;
# echo "$IP_ADDRESS is pingable"
timeout 5 nc -z $IP_ADDRESS 22 > /dev/null 2>&1 || exit 0;
# echo "$IP_ADDRESS is sshable"
# 
ssh-keygen -R $IP_ADDRESS > /dev/null 2>&1 || true
ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts 2>&1 || true
# echo "$IP_ADDRESS is known hosts"
timeout 5 ssh \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "hostname" > /dev/null 2>&1 || exit 0;
# echo "$IP_ADDRESS is sshable"
PRODUCT_NAME=$(ssh \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "dmidecode" | grep "Product Name:" | head -n1 | sed 's/Product Name: //g' \
    | sed "s/[^[:alnum:]-]/-/g" \
    | sed -e "s/^-//g" \
    | sed -e "s/-$//g" \
    | tr '[:upper:]' '[:lower:]')
# echo "192.168.1.$i 0 $PRODUCT_NAME"
# echo "PRODUCT_NAME: $PRODUCT_NAME"
timeout 5 ssh \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS \
    "stat /var/log/fai/localhost/last/boot.log" > /dev/null 2>&1 || exit 0
# echo "$IP_ADDRESS is faiable"
BOOT_TIME=$(ssh \
    -i "$IDENTIFY_FILE" \
    -o PasswordAuthentication=no \
    $IP_ADDRESS "stat -c %W /var/log/fai/localhost/last/boot.log")
echo "$IP_ADDRESS $BOOT_TIME $PRODUCT_NAME"
