#!/bin/bash
set -e
args=("$@")
ISO_FILE=${args[0]}
if [ -z "$ISO_FILE" ]; then
    echo "ISO_FILE is empty"
    exit 1
fi
echo "ISO_FILE: $ISO_FILE"
echo "Provisioning on metal machine"
make -v || \
    apt install -y make
ansible-playbook --version > /dev/null 2>&1 || \
    apt install -y ansible
pip3 --version > /dev/null 2>&1 || \
    apt install -y python3-pip
python3 --version || apt install -y python3
xorriso -version > /dev/null 2>&1 || apt install -y xorriso
echo
apt install python3.11-venv -y
(cd /root/picloud/metal/roles/pxe_server/files/ && docker compose down) || true;
rm -rf ./metal/roles/pxe_server/files/data/os/ || true
stat venv > /dev/null 2>&1 || python3 -m venv venv
source ./venv/bin/activate
ansible --version
echo
pip install docker
pip install ansible
pip install netaddr
# pip install docker-compose
cp $ISO_FILE ./metal/roles/pxe_server/files/data/iso/image.iso
echo
export env=prod
(cd ./metal/ && 	ansible-playbook \
		--inventory inventories/${env}.yml \
		boot.yml)
(cd /root/picloud/metal/roles/pxe_server/files/ && docker compose up)
