#!/bin/bash

set -xeo pipefail
hostnameI=$(./pic hostname)
TFTP_FOLDER="/srv/tftp/fai/"
VMLINUZ_FILE=`docker exec fai-cd bash -c "ls $TFTP_FOLDER | grep vmlinuz"`
INITRD_FILE=`docker exec fai-cd bash -c "ls $TFTP_FOLDER | grep initrd"`

echo "default fai-generated" > ./fai/pxelinux.cfg/default

echo "label fai-generated" >> ./fai/pxelinux.cfg/default
echo "kernel $VMLINUZ_FILE" >> ./fai/pxelinux.cfg/default
echo "append initrd=$INITRD_FILE ip=dhcp root=live:http://$hostnameI:8085/squash.img rootovl FAI_FLAGS=sshd FAI_CONFIG_SRC=file:///var/lib/fai/config FAI_ACTION=install"
echo "append initrd=$INITRD_FILE ip=dhcp root=/srv/fai/nfsroot:vers=3 rootovl FAI_FLAGS=verbose,sshd,createvt FAI_CONFIG_SRC=nfs://faiserver/srv/fai/config FAI_ACTION=install" >> ./fai/pxelinux.cfg/default

sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+,proxy/$hostnameI,proxy/g" ./dnsmasq.conf
sed -i "s/pxeserver,[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/pxeserver,$hostnameI/g" ./dnsmasq.conf

docker restart fai-cd
docker exec -it fai-cd bash -c "ln -s /srv/fai/config /var/www/html/" || true
docker rm -f fai-nginx || true
(lsof -i:80 && echo "Port 80 is in use" && exit 1) || true
docker run --name fai-nginx -p 8085:80 -v /var/www/html/:/usr/share/nginx/html:ro -d nginx
# 
docker exec fai-nginx bash -c "du -h /usr/share/nginx/html/squash.img"
PXE_SERVER_IP_ADDRESS=$(./pic hostname)
echo "PXE_SERVER_IP_ADDRESS: $PXE_SERVER_IP_ADDRESS"
SQUASH_IMG_URL="http://$PXE_SERVER_IP_ADDRESS:8085/squash.img"
CURL_HEAD_SQUASH_IMG=$(curl -s -I $SQUASH_IMG_URL -X HEAD -w '%{http_code}' -o /dev/null)
echo "CURL_HEAD_SQUASH_IMG: $CURL_HEAD_SQUASH_IMG"
if [ "$CURL_HEAD_SQUASH_IMG" == "200" ]; then
    echo "Squash.img is ready. Starting to boot node: $SQUASH_IMG_URL"
else
    echo "Squash.img is not ready. Waiting for it to be ready: $SQUASH_IMG_URL"
    exit 1
fi
chown root ./tmp-dnsmasq.log
docker exec fai-cd bash -c "echo > /tmp/dnsmasq.log || true"
docker exec fai-cd bash -c "dnsmasq"
