#!/bin/bash
set -xeo pipefail
args=("$@")
URL=${args[0]}

if [ -z "$URL" ]; then
    echo "URL is empty. Specify a URL to download."
    echo "Usage: ./pic download URL"
    exit 1
fi
wget -c $URL

mv $(basename $URL) ./fai/
echo "Downloaded $URL to ./fai/$(basename $URL)"

(cd ./fai/ && tar -xvf $(basename $URL))
sed -i 's/mirror.netcologne.de/127.0.0.1:9999/' ./fai/fai-bookworm/apt/sources.list
sed -i 's/mirror.netcologne.de/127.0.0.1:9999/' ./fai/fai-bookworm/nfsroot.conf
sed -i 's/\/srv\/fai\/nfsroot-bookworm/\/srv\/fai\/nfsroot/' ./fai/fai-bookworm/nfsroot.conf
sed -i 's/,createvt//' ./fai/fai-bookworm/grub.cfg
sed -i 's/,createvt//' ./fai/fai-bookworm/grub.cfg.autodiscover
