#!/bin/bash
set -e
args=("$@")
MAC_ADDRESS=${args[0]}
if [ -z "$MAC_ADDRESS" ]; then
    echo "MAC_ADDRESS is empty"
    exit 1
fi
IDENTITY_FILE=${args[1]}
if [ -z "$IDENTITY_FILE" ]; then
    echo "IDENTITY_FILE is empty"
    exit 1
fi
while true; do
    wakeonlan $MAC_ADDRESS > /dev/null 2>&1 || true
    echo
    echo "Make sure your client machine is turned off before running this script"
    sleep 3
    DNSMASQ_LOG=$(docker exec fai bash -c "tail -n100 /tmp/dnsmasq.log")
    echo "DNSMASQ_LOG: $DNSMASQ_LOG"
    MAC_ADDRESS_LOWER=$(echo $MAC_ADDRESS | tr '[:upper:]' '[:lower:]')
    MATCH_LINE=$(echo "$DNSMASQ_LOG" | grep "PXE(" | grep "$MAC_ADDRESS_LOWER pxelinux.0") || true
    if [ -z "$MATCH_LINE" ]; then
        continue
    fi
    echo "MATCH_LINE: $MATCH_LINE"
    IP_ADDRESS=$(echo $MATCH_LINE | awk '{print $7}')
    echo "IP_ADDRESS: $IP_ADDRESS"
    # validate IP_ADDRESS
    if [[ $IP_ADDRESS == 192.168.* ]]; then
        break
    fi
done
echo "IP_ADDRESS: $IP_ADDRESS"
# Wait for node to be shutdown
while true; do
    wakeonlan $MAC_ADDRESS > /dev/null 2>&1 || true
    echo "Sending installation"
    sleep 2
    ping -c1 "$IP_ADDRESS" > /dev/null 2>&1 && break || continue;
done
# while true; do
#     echo "Waiting for node to be shutdown"
#     ping -c1 "$IP_ADDRESS" > /dev/null 2>&1 || break;
#     sleep 8
# done
FILESIZE_IN_MB=$(docker exec fai bash -c "stat -c '%s' /var/www/html/squash.img" | awk '{print $1}')
while true; do
    echo "Downloading squash.img ($FILESIZE_IN_MB, this may take a while)"
    sleep 16
    nc -z -w 1 "$IP_ADDRESS" 22 > /dev/null 2>&1 && break || continue;
done
echo "SSH is ready"
while true; do
    echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") SSH is ready."
    sleep 12
    ssh-keygen -R "$IP_ADDRESS" > /dev/null 2>&1 || true
    ssh-keyscan "$IP_ADDRESS" >> ~/.ssh/known_hosts > /dev/null 2>&1 > /dev/null 2>&1 || true
    (timeout 10 ssh \
        -o PasswordAuthentication=no \
        -o StrictHostKeyChecking=no \
        -i $IDENTITY_FILE root@$IP_ADDRESS "echo 'The node is ready'" > /dev/null 2>&1) && break || continue;
done
docker restart fai
while true; do
    echo "Waiting for finish installation"
    ping -c1 "$IP_ADDRESS" > /dev/null 2>&1 || break;
    sleep 6
done
echo "  Node is installed successfully. Rebooting the node"
while true; do
    wakeonlan $MAC_ADDRESS > /dev/null 2>&1 || true
    # echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") SSH is ready. Waiting for private key to be ready"
    sleep 2
    (timeout 2 ssh \
        -o PasswordAuthentication=no \
        -o StrictHostKeyChecking=no \
        -i $IDENTITY_FILE root@$IP_ADDRESS "echo" > /dev/null 2>&1) && break || continue;
done
ssh-keygen -R "$IP_ADDRESS" > /dev/null 2>&1 || true
ssh-keyscan "$IP_ADDRESS" >> ~/.ssh/known_hosts > /dev/null 2>&1 > /dev/null 2>&1 || true
echo
ssh -i $IDENTITY_FILE root@$IP_ADDRESS "cat /etc/os-release"
echo "Now you can SSH to the node with this command:"
echo "  ssh -i $IDENTITY_FILE $IP_ADDRESS"

