#!/bin/bash
set -e -o pipefail
source .env
args=("$@")
IDENTIFY_FILE=${args[0]}
if [ -z "$IDENTIFY_FILE" ]; then
    echo "Please provide the identify file"
    exit 1
fi

curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.5.3/scripts/environment_check.sh | bash
helm repo add longhorn https://charts.longhorn.io
helm repo update
kubectl get namespace longhorn-system || kubectl create namespace longhorn-system
# set defaultSettings.defaultReplicaCount to 1
helm install longhorn longhorn/longhorn --namespace longhorn-system \
    --set defaultSettings.defaultReplicaCount=1
