#!/bin/bash
set -e -o pipefail
source .env
if [ -z "$DOMAIN" ]; then
    echo "Please set DOMAIN in .env"
    exit 1
fi
echo "Installing S3"
helm repo add minio https://charts.min.io/
# ,rootUser=rootuser,rootPassword=$ROOT_PASSWORD
helm install --set users[0].accessKey=accessKey,users[0].secretKey=secretKey,users[0].policy=readwrite,resources.requests.memory=512Mi minio minio/minio
helm get notes minio
rootUsername=$(kubectl get secret --namespace default minio -o jsonpath="{.data.rootUser}" | base64 --decode)
rootPassword=$(kubectl get secret --namespace default minio -o jsonpath="{.data.rootPassword}" | base64 --decode)
TUNNEL_NAMESPACE=default ./pic expose http minio-console.gitlab-ns 9001
TUNNEL_NAMESPACE=default ./pic expose http minio.gitlab-ns 9000
echo "Minio root username: $rootUsername"
echo "Minio root password: $rootPassword"
echo "Minio console: https://http-minio-console-9001.$DOMAIN/login"