#!/bin/bash
set -e -o pipefail
source .env
if [ -z "$DOMAIN" ]; then
    echo "Please set DOMAIN in .env"
    exit 1
fi
echo "Installing S3"
curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-5.0.10.tgz
curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/tenant-5.0.10.tgz
# helm uninstall minio-operator -n minio-operator || true
helm upgrade --install \
    --namespace minio-operator \
    --create-namespace \
    minio-operator operator-5.0.10.tgz
rm operator-5.0.10.tgz
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
EOF
kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode;echo
TUNNEL_NAMESPACE=default ./pic expose http console.minio-operator 9090 200
# 
PIC_DIR="$HOME/.pic"
helm uninstall tenant-picloud -n tenant-ns || true
kubectl get pvc --namespace tenant-ns -o name | xargs kubectl delete --namespace tenant-ns || true
stat $PIC_DIR/s3.json > /dev/null 2>&1 || \
    ACCESS_KEY_ID=$(openssl rand -hex 32)
stat $PIC_DIR/s3.json > /dev/null 2>&1 || \
    SECRET_ACCESS_KEY=$(openssl rand -hex 32)
stat $PIC_DIR/s3.json > /dev/null 2>&1 || \
    jq -n --arg ACCESS_KEY_ID "$ACCESS_KEY_ID" --arg SECRET_ACCESS_KEY "$SECRET_ACCESS_KEY" '{"ACCESS_KEY_ID":$ACCESS_KEY_ID,"SECRET_ACCESS_KEY":$SECRET_ACCESS_KEY}' > $PIC_DIR/s3.json
ACCESS_KEY_ID=$(jq -r '.ACCESS_KEY_ID' $PIC_DIR/s3.json)
SECRET_ACCESS_KEY=$(jq -r '.SECRET_ACCESS_KEY' $PIC_DIR/s3.json)
    # --set global.registry.bucket=gitlab-registry \
    # --set global.appConfig.object_store.enabled=true \
    # --set global.appConfig.object_store.proxy_download=true \
    # --set global.appConfig.object_store.connection.secret=gitlab-storage \
    # --set global.appConfig.object_store.connection.key=connection \
    # --set global.appConfig.lfs.bucket=gitlab-lfs-storage \
    # --set global.appConfig.artifacts.bucket=gitlab-artifacts-storage \
    # --set global.appConfig.uploads.bucket=gitlab-uploads-storage \
    # --set global.appConfig.packages.bucket=gitlab-packages-storage \
    # --set global.appConfig.externalDiffs.bucket=gitlab-external-diffs \
    # --set global.appConfig.terraformState.bucket=gitlab-terraform-state \
    # --set global.appConfig.dependencyProxy.bucket=gitlab-dependency-proxy \
    # --set global.appConfig.backups.bucket=gitlab-backup-upload \
    # --set global.appConfig.backups.tmpBucket=gitlab-tmp-storage \
    # --set gitlab.toolbox.backups.objectStorage.config.secret=gitlab-storage \
    # --set gitlab.toolbox.backups.objectStorage.config.key=connection \
    # --set registry.storage.secret=gitlab-registry-storage \
    # --set registry.storage.key=connection \
helm upgrade --install \
    --namespace tenant-ns \
    --create-namespace \
    --set 'tenant.buckets[0].name=gitlab-registry,tenant.buckets[1].name=gitlab-lfs-storage,tenant.buckets[2].name=gitlab-artifacts-storage,tenant.buckets[3].name=gitlab-uploads-storage,tenant.buckets[4].name=gitlab-packages-storage,tenant.buckets[5].name=gitlab-external-diffs,tenant.buckets[6].name=gitlab-terraform-state,tenant.buckets[7].name=gitlab-dependency-proxy,tenant.buckets[8].name=gitlab-backup-upload,tenant.buckets[9].name=gitlab-tmp-storage' \
    --set "tenant.pools[0].storageclassName=local-path,tenant.pools[0].servers=2,tenant.name=tenant-picloud" \
    --set "secrets.accessKey=$ACCESS_KEY_ID" \
    --set "secrets.secretKey=$SECRET_ACCESS_KEY" \
    tenant-picloud tenant-5.0.10.tgz
rm tenant-5.0.10.tgz
while true; do
    kubectl -n tenant-ns get svc tenant-picloud-hl && break || sleep 5
done
TUNNEL_NAMESPACE=default ./pic expose https tenant-picloud-hl.tenant-ns 9000 400
# exit 0
# helm repo add minio https://charts.min.io/
# # ,rootUser=rootuser,rootPassword=$ROOT_PASSWORD
# helm install --set users[0].accessKey=accessKey,users[0].secretKey=secretKey,users[0].policy=readwrite,resources.requests.memory=512Mi minio minio/minio
# helm get notes minio
# rootUsername=$(kubectl get secret --namespace default minio -o jsonpath="{.data.rootUser}" | base64 --decode)
# rootPassword=$(kubectl get secret --namespace default minio -o jsonpath="{.data.rootPassword}" | base64 --decode)
# # kubectl --namespace minio-operator port-forward svc/console 9090:9090
# TUNNEL_NAMESPACE=default ./pic expose http minio 9000
#   kubectl --namespace tenant-ns port-forward svc/myminio-console 9443:9443
# echo "Minio root username: $rootUsername"
# echo "Minio root password: $rootPassword"
echo "Minio console: https://http-console-minio-operator-9090.$DOMAIN/"
