#!/bin/bash
source .env
set -e -o pipefail
args=("$@")
IDENTIFY_FILE=${args[0]}
PIC_DIR="$HOME/.pic"
./pic recommended1 $IDENTIFY_FILE
timeout 600 ./pic wait deploy pic-test-csi-s3 default Available
timeout 20 kubectl logs deploy/pic-test-csi-s3 -f || true

# 
time (./pic redis | tee $LOGS_DIR/redis.log) &
time (./pic install-minio | tee $LOGS_DIR/s3.log) &
wait

TUNNEL_NAMESPACE=default ./pic expose http console.minio-operator 9090 200
TUNNEL_NAMESPACE=default ./pic expose http tenant-picloud-hl.tenant-ns 9000 400 "" "true"

./pic expose http harbor-registry.harbor-ns 5000 "200" "" "true"
GITLAB_ROOT_GENERATED_PASSWORD=$(jq -r '.gitlab_root_generated_password' "$HOME/.pic/gitlab.json")
while true; do
    echo $GITLAB_ROOT_GENERATED_PASSWORD | docker login http-harbor-registry-harbor-ns-5000.$DOMAIN --username root --password-stdin && break;
    echo "Retrying to login to harbor"
    sleep 2
done

# 
echo "FROM scratch" > busybox.Dockerfile;docker build -t http-harbor-registry-harbor-ns-5000.$DOMAIN/busybox -f busybox.Dockerfile .;rm busybox.Dockerfile
while ! docker push http-harbor-registry-harbor-ns-5000.$DOMAIN/busybox; do
    echo "Retrying to push to harbor"
    sleep 2
done
