#!/bin/bash
source .env
set -xeo pipefail
args=("$@")
IDENTIFY_FILE=${args[0]}
PIC_DIR="$HOME/.pic"
LOGS_DIR="$PIC_DIR/logs"
echo "Installing k3s recommended packages 1"
./pic recommended2 $IDENTIFY_FILE

( time (./pic auto-join $IDENTIFY_FILE | tee $LOGS_DIR/auto-join.log))

time (./pic redis | tee $LOGS_DIR/redis.log)
# wait $(jobs -p)

TUNNEL_NAMESPACE=default ./pic expose http console.minio-operator 9090 200
TUNNEL_NAMESPACE=default ./pic expose http tenant-picloud-hl.tenant-ns 9000 400 "" "true"

./pic expose http harbor-registry.harbor-ns 5000 "200" "" "true"
