#!/bin/bash
source .env
set -e -o pipefail
args=("$@")
IDENTIFY_FILE=${args[0]}
PIC_DIR="$HOME/.pic"
LOGS_DIR="$PIC_DIR/logs/"
echo "Installing k3s recommended packages"
./pic recommended1 $IDENTIFY_FILE
# 
GITLAB_ROOT_GENERATED_PASSWORD=$(jq -r '.gitlab_root_generated_password' "$HOME/.pic/gitlab.json")
( time ./pic grafana-promtail-loki "lokiadmin" "$GITLAB_ROOT_GENERATED_PASSWORD" | tee $LOGS_DIR/grafana-promtail-loki.log) &
wait

TUNNEL_NAMESPACE=default ./pic expose http grafana.loki 80
TUNNEL_NAMESPACE=default ./pic expose http tenant-picloud-hl.tenant-ns 9000 400 "" "true"
TUNNEL_NAMESPACE=gitlab-ns ./pic expose http gitlab-webservice-default.gitlab-ns    8181    404
./pic wait pod          redis-replicas-1                    default Ready
./pic wait pod          redis-replicas-2                    default Ready
TUNNEL_NAMESPACE=default ./pic expose tcp redis-master.default 6379
wait
./pic dump-images

echo "./pic has installed your recommended packages"
# This takes 21m6s on 3 nodes
rm -rf $LOGS_DIR/reinstall-k3s.log
rm -rf $LOGS_DIR/harbor.log
rm -rf $LOGS_DIR/gitlab.log
rm -rf $LOGS_DIR/s3.log
rm -rf $LOGS_DIR/redis.log
rm -rf $LOGS_DIR/install-longhorn.log
exit 0
