#!/bin/bash

set -xeo pipefail

RUNNING_VMS_NAMES=`VBoxManage list vms | awk '{print $1}'`
for VM_NAME in $RUNNING_VMS_NAMES; do
    echo "VM_NAME: $VM_NAME"
    VM_NAME=${VM_NAME//\"/}
    if [ "<inaccessible>" == "$VM_NAME" ]; then
        continue
    fi
    # VBoxManage controlvm $VM_NAME acpipowerbutton
    # delete vm
    VBoxManage unregistervm $VM_NAME --delete
done
BASE_FOLDER="$HOME/VirtualBox VMs/"
rm -rf "$BASE_FOLDER"
echo "All VMs are stopped and deleted"
