#!/bin/bash
set -x
kubectl rollout restart deploy coredns -n kube-system

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager \
  --set crds.enabled=true \
  --namespace cert-manager  \
  --create-namespace

kubectl get ns redpanda || kubectl create ns redpanda

helm repo add redpanda https://charts.redpanda.com
helm repo update
helm uninstall redpanda --namespace redpanda
helm install redpanda redpanda/redpanda \
  --version 5.9.19 \
  --namespace redpanda


kubectl -n redpanda rollout status statefulset redpanda --watch
