#!/bin/bash
helm repo add jetstack https://charts.jetstack.io
helm repo add redpanda https://charts.redpanda.com
helm repo update

kubectl get ns redpanda || kubectl create ns redpanda
helm uninstall cert-manager --namespace cert-manager
helm uninstall redpanda --namespace redpanda
kubectl delete secret cert-manager-webhook-ca -n redpanda

set -xe
kubectl rollout restart deploy coredns -n kube-system
kubectl rollout status deployment/coredns -n kube-system --watch

# 
helm install redpanda redpanda/redpanda \
  --set tls.enabled=false \
  --set external.enabled=false \
  --version 5.9.19 \
  --namespace redpanda
kubectl -n redpanda rollout status statefulset redpanda --watch

./pic declare-project-variables root%2FProvision TF_VAR_CERT_MANAGER_WEBHOOK_CA "`kubectl get secrets -n cert-manager cert-manager-webhook-ca  -o jsonpath="{.data.ca\.crt}" | base64 -d`"  "production" "false"

kubectl delete pod kcat -n redpanda
kubectl run -n redpanda kcat --rm -ti --restart=Never --image=confluentinc/cp-kafkacat -- bash -c "echo 1 | kafkacat -b redpanda.redpanda:9093 -t msgs -P -c 1; echo DONE"
