#!/bin/bash
source .env
set -e -o pipefail
echo "Installing Redis"
helm repo add bitnami https://charts.bitnami.com/bitnami || echo ""
# kubectl get namespace redis-ns || kubectl create namespace redis-ns
PASSWORD=$(openssl rand -base64 32)
echo "{}" > redis.json
helm upgrade --install redis oci://registry-1.docker.io/bitnamicharts/redis \
 --set global.storageClass="local-path",global.redis.password="$PASSWORD" --set master.disableCommands="",replica.disableCommands=""
jq --arg password "$PASSWORD" '.redis.password = $password' redis.json > redis.json.tmp && mv redis.json.tmp redis.json
jq --arg hostname "tcp-redis-master-6379.$DOMAIN" '.redis.host = $hostname' redis.json > redis.json.tmp && mv redis.json.tmp redis.json
./pic wait pod          redis-master-0                      default Ready
./pic wait pod          redis-replicas-0                    default Ready
