#!/bin/bash
set -xe

PIC_DIR="$HOME/.pic"
stat $PIC_DIR/rabbitmq.json || \
    jq -n \
    --arg RABBITMQ_AUTH_PASSWORD "`openssl rand -hex 16`" \
    --arg RABBITMQ_AUTH_USERNAME "root" \
        '{"rabbitmq_auth_password":$RABBITMQ_AUTH_PASSWORD,"rabbitmq_auth_username":$RABBITMQ_AUTH_USERNAME}' > $PIC_DIR/rabbitmq.json
PASSWORD=$(jq -r '.rabbitmq_auth_password' "$PIC_DIR"/rabbitmq.json)

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

helm upgrade --install rabbitmq bitnami/rabbitmq \
  --namespace rabbitmq \
  --create-namespace \
  --set auth.username=root,auth.password=$PASSWORD,persistence.enabled=true,persistence.size=10Gi

