#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if [ -f $FAI/files/root-ssh-key ]; then
    mkdir -m 0700 -p $target/root/.ssh
    install -vpm 0600 $FAI/files/root-ssh-key $target/root/.ssh/authorized_keys
fi

if [ -f $FAI/files/postinst ]; then
    install -vpm 0700 $FAI/files/postinst $target/usr/local/bin/$postinst
fi
if [ X$rclocal = X1 ] && [ -n "$postinst" ]; then
    cat <<EOM > $target/etc/rc.local
#! /bin/bash

/usr/local/bin/$postinst
rm -f /etc/rc.local
EOM
    chmod a+rx $target/etc/rc.local
fi

exit $error

