#!/bin/bash
set -e -o pipefail
echo
source .env
args=("$@")
SSH_PUB_KEY=${args[0]}
# 
GITLAB_TOKEN=$(./pic get-refresh-token-gitlab)
export FQDN_RECORD="http-gitlab-webservice-default-gitlab-ns-8181.$DOMAIN"
curl --request GET --header "Authorization: Bearer $GITLAB_TOKEN" \
    "https://$FQDN_RECORD/api/v4/user/keys"
echo "SSH_PUB_KEY: $SSH_PUB_KEY"

PAYLOAD=$(jq -c -n --arg SSH_PUB_KEY "$SSH_PUB_KEY" '{"title":"gitlab-ssh-key","key":$SSH_PUB_KEY}')
echo $PAYLOAD > gitlab-ssh-key.json
curl --request POST --header "Authorization: Bearer $GITLAB_TOKEN" \
    --header "Content-Type: application/json" \
    --data "@gitlab-ssh-key.json" \
    "https://$FQDN_RECORD/api/v4/user/keys"
rm gitlab-ssh-key.json
echo