#!/bin/bash
set -e -o pipefail
echo
source .env
FQDN_ADDRESS="http-gitlab-webservice-default-gitlab-ns-8181.$DOMAIN"
args=("$@")
PROJECT_NAME=${args[0]}
KEY=${args[1]}
VALUE=${args[2]}
ENVIRONMENT_SCOPE=${args[3]}
MASKED=${args[4]}
if [ -z "$PROJECT_NAME" ]; then
    echo "PROJECT_NAME is empty"
    exit 1
fi
if [ -z "$KEY" ]; then
    echo "KEY is empty"
    exit 1
fi
if [ -z "$VALUE" ]; then
    echo "VALUE is empty"
    exit 1
fi
if [ -z "$ENVIRONMENT_SCOPE" ]; then
    ENVIRONMENT_SCOPE="*"
fi
if [ -z "$MASKED" ]; then
    MASKED="true"
fi
URL="https://$FQDN_ADDRESS/api/v4/projects/$PROJECT_NAME/variables"
echo "URL: $URL"

GITLAB_TOKEN=$(./pic get-refresh-token-gitlab)
PAYLOAD=$(jq --null-input \
    --arg value "$VALUE" \
    --arg key "$KEY" \
    --argjson raw true \
    --argjson masked $MASKED \
    --argjson protected true \
    --arg environment_scope "$ENVIRONMENT_SCOPE" \
    '{value: $value, key: $key, raw: $raw, masked: $masked, protected: $protected, environment_scope: $environment_scope}')
# echo "PAYLOAD: $PAYLOAD"
MIRROR=$(curl -s --request POST \
    --header "Content-Type: application/json" \
    --data "$PAYLOAD" \
    --header "Authorization: Bearer $GITLAB_TOKEN" \
    $URL)

echo "MIRROR: $MIRROR"