#!/bin/bash
set -e -o pipefail
source .env
if [ -z "$DOMAIN" ]; then
    echo "Please set DOMAIN in .env"
    exit 1
fi
if [ -z "$EMAIL" ]; then
    echo "Please set EMAIL in .env"
    exit 1
fi
set -e -o pipefail
args=("$@")
IDENTIFY_FILE=${args[0]}
helm repo add harbor https://helm.goharbor.io
GITLAB_ROOT_GENERATED_PASSWORD=$(jq -r '.gitlab_root_generated_password' "$HOME/.pic/gitlab.json")
# mount ~/.pic/harbor-registry-data
mkdir -p ~/.pic/harbor-registry-data
kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-data
  namespace: harbor-ns
spec:
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: ~/.pic/harbor-registry-data
EOF
kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-data
  namespace: harbor-ns
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
EOF

helm upgrade --install harbor harbor/harbor  -n harbor-ns --create-namespace \
    --set registry.credentials.username=root \
    --set persistence.persistentVolumeClaim.registry.existingClaim=harbor-registry-data \
    --set registry.credentials.password=$GITLAB_ROOT_GENERATED_PASSWORD


./pic wait deployment harbor-registry harbor-ns Available

kubectl get secret regcred --namespace default || \
    kubectl create secret docker-registry regcred \
    --docker-server=http-harbor-registry-harbor-ns-5000.$DOMAIN --docker-username=root --docker-password=$GITLAB_ROOT_GENERATED_PASSWORD --namespace default
