#!/bin/bash

set -eo pipefail
args=("$@")
ORG_NAME=${args[0]}
PAT=${args[1]}
if [ -z "$PAT" ]; then
    echo "PAT is required"
    exit 1
fi
IDENTITY_FILE=${args[2]}
if [ -z "$ORG_NAME" ]; then
    echo "ORG_NAME is required"
    exit 1
fi
if [ -z "$IDENTITY_FILE" ]; then
    echo "IDENTITY_FILE is required"
    exit 1
fi
if [ ! -f "$IDENTITY_FILE" ]; then
    echo "IDENTITY_FILE does not exist"
    exit 1
fi
EXCLUDES=${args[3]}
if [ -z "$EXCLUDES" ]; then
    EXCLUDES=""
fi
API_URL="https://api.github.com/orgs/$ORG_NAME/repos"
# curl -X GET -u "$ORG_NAME:$PAT" "$API_URL" | jq -r '.[]'
full_names=$(curl -s -X GET -u "$ORG_NAME:$PAT" "$API_URL")
full_names=$(echo $full_names | jq -r '.[] | select(.archived == false)')
#  | jq -r '.[] | .full_name'
full_names=$(echo $full_names | jq -r '.full_name')
for EXCLUDE in $EXCLUDES; do
    PATH_TO_EXCLUDE="$ORG_NAME/$EXCLUDE"
    full_names_new=""
    for REPO in  $full_names;
    do
        if [[ "$REPO" == "$PATH_TO_EXCLUDE" ]]; then
            echo "Skip $REPO"
            continue
        fi
        full_names_new="$full_names_new $REPO"
    done
    full_names="$full_names_new"
done
# echo "full_names: $full_names"
ssh-keygen -R github.com
ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
MSG=$(ssh -T -i "$IDENTITY_FILE" git@github.com 2>&1 || true)
if [[ "$MSG" != *"successfully authenticated"* ]]; then
    echo "ERROR: $MSG"
    exit 1
fi
echo "MSG: $MSG"
# 
GITHUB_AUTH="git:$PAT"
for REPO in  $full_names;
do
    REPO_NAME=$(basename $REPO)
    if [ -d "../$REPO_NAME" ]; then
        echo "REPO_NAME: $REPO_NAME"
    fi
    PROJECT_NAME=$(echo $REPO_NAME)
    # if PROJECT_NAME is starts with dot, skip
    if [[ "$PROJECT_NAME" == .* ]]; then
        echo "Skip $PROJECT_NAME"
        continue
    fi
    echo "PROJECT_NAME: $PROJECT_NAME"
    while ! ./pic git-folk git@github.com:$REPO.git "$IDENTITY_FILE" ".."; do
        echo "Retrying..."
        sleep 60
    done
done
# 
while true; do
    sleep 15
    echo "Waiting for pic to be ready"
    SHOULD_CONTINUE=false
    for REPO in  $full_names;
    do
        REPO_NAME=$(basename $REPO)

        if [[ "$REPO_NAME" == .* ]]; then
            echo "Skip $REPO_NAME"
            continue
        fi
        ./pic succeed-pipeline root%2F$REPO_NAME develop || SHOULD_CONTINUE=true
        if [ "$SHOULD_CONTINUE" = true ]; then
            echo
            echo "$REPO is not ready"
            break
        fi
        echo "Processing $REPO"
    done
    if [ "$SHOULD_CONTINUE" = true ]; then
        continue
    fi
    break;
done

echo "Done"
